name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/neutron
          ref: 6facecf3615c2a24596a325354d960a7228f45a9 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/neutron-dynamic-routing
          ref: 19962074d036514154d6c3c6cd307b3faea378d6 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/neutron-fwaas
          ref: c09b517dc2a43abe7e3d8d5a68c6e9e82db5baeb # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/neutron-vpnaas
          ref: a8506e6fc5835b8ab1e7b1522a78832ba16e8195 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/networking-baremetal
          ref: 7b532a8906622c4e7b8cc9b6209cbb1067bdc9b8 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/networking-generic-switch
          ref: 42c59790d62a3ece7c9674a678a20e3ddf80b5b1 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: vexxhost/neutron-policy-server
          ref: a215317bfa147f29dd4e85ff96a54982384c8ba1 # main

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: vexxhost/neutron-ovn-network-logging-parser
          ref: 392a445022a87fb460f113bd5e3315760da105e7 # main

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: openstack/tap-as-a-service
          ref: 9cb269a3a4b6b999d73b26208d1501f572162076 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          repository: vexxhost/atmosphere
          ref: main
          path: vexxhost/atmosphere

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@b6113e0668dc85929f783667f0347fc76b272844 # main
        with:
          image-name: neutron
          build-contexts: |
            neutron=openstack/neutron
            neutron-dynamic-routing=openstack/neutron-dynamic-routing
            neutron-fwaas=openstack/neutron-fwaas
            neutron-vpnaas=openstack/neutron-vpnaas
            networking-baremetal=openstack/networking-baremetal
            networking-generic-switch=openstack/networking-generic-switch
            neutron-policy-server=vexxhost/neutron-policy-server
            neutron-ovn-network-logging-parser=vexxhost/neutron-ovn-network-logging-parser
            tap-as-a-service=openstack/tap-as-a-service
            ovsinit-src=vexxhost/atmosphere/crates/ovsinit
          push: ${{ github.event_name != 'pull_request' }}
